name: Continuous Integration using openmodelica-library-testing-action

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
    tags: '*'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        omc-version: ['stable']
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Update pip
        run: |
          pip install --upgrade pip

      - name: Setup OpenModelica
        uses: AnHeuermann/setup-openmodelica@v0.7
        with:
          version: ${{ matrix.omc-version }}
          packages: |
            omc
          libraries: |
            Modelica 3.2.1
            ModelicaAdditions 1.5
          omc-diff: true

      - name: openmodelica-library-testing
        uses: AnHeuermann/openmodelica-library-testing-action@main
        id: library-testing
        with:
          library: 'PNlib'
          library-version: '1.1'
          modelica-file: PNlib/package.mo
          omc-version: ${{ matrix.omc-version }}
          pages-root-url: 'https://anheuermann.github.io/ExampleModelicaLibrary/'

  deploy:
    needs: test
    permissions:
      contents: write
    if: ${{ always() }}
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get HTML artifact
        uses: actions/download-artifact@v4
        with:
          path: html/
          pattern: '*.html'
          merge-multiple: true

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: html/
          branch: gh-pages
