name: Continuous Integration using openmodelica-library-testing-action

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
    tags: '*'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        omc-version: ['stable']
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Update pip
        run: |
          pip install --upgrade pip

      - name: Setup OpenModelica
        uses: AnHeuermann/setup-openmodelica@v0.7
        with:
          version: ${{ matrix.omc-version }}
          packages: |
            omc
          libraries: |
            Modelica 3.2.0
            ModelicaAdditions 1.5
          omc-diff: true

      - name: openmodelica-library-testing
        uses: AnHeuermann/openmodelica-library-testing-action@main
        id: library-testing
        with:
          package-name: 'PNlib'
          package-version: '1.0'
          modelica-file: PNlib.mo
          omc-version: ${{ matrix.omc-version }}

  deploy:
    needs: test
    permissions:
      contents: write
    if: ${{ always() }}
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'
          clean: false

      - name: Get HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: PNlib-${{ github.run_id }}.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: '.'
          branch: gh-pages