name: Continuous Integration using openmodelica-library-testing-action

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
    tags: '*'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        omc-version: ['1.19', 'stable']
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip            # caching pip dependencies

      - name: Update pip
        run: |
          pip install --upgrade pip

      - name: Setup OpenModelica
        uses: AnHeuermann/setup-openmodelica@v0.7
        with:
          version: ${{ matrix.omc-version }}
          packages: |
            omc
          libraries: |
            Modelica 3.2.0
            ModelicaAdditions 1.5
          omc-diff: true

      - name: openmodelica-library-testing
        uses: AnHeuermann/openmodelica-library-testing-action@main
        id: library-testing
        with:
          package-name: PNlib
          package-version: '1.0'
          modelica-file: PNlib.mo
          omc-version: ${{ matrix.omc-version }}
          publish-gh-pages: true
          gh-pages-ref: gh-pages
          pages-root-url: https://AnHeuermann.github.io/ExampleModelicaLibrary
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
